# Generated by Django 2.2.5 on 2019-09-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('chosen_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ShirtSize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.PositiveIntegerField()),
                ('card_token', models.CharField(max_length=256)),
                ('captcha_token', models.CharField(max_length=512)),
                ('product_instances', models.ManyToManyField(to='store.ProductInstance')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(to='store.ShirtSize'),
        ),
    ]
