# Generated by Django 2.2.5 on 2019-09-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190911_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='foo', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinstance',
            name='sku',
            field=models.TextField(default='foo', max_length=512),
            preserve_default=False,
        ),
    ]
