# Generated by Django 2.2.5 on 2019-09-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190915_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dj_order_id',
            field=models.CharField(default='yo', max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gooten_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
