# Generated by Django 2.2.5 on 2019-09-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_instances', to='store.Product'),
        ),
    ]
