# Generated by Django 3.0.1 on 2019-12-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20191106_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'processing'), ('s', 'shipped'), ('d', 'delivered')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default=12345, max_length=10),
            preserve_default=False,
        ),
    ]
