# Generated by Django 3.0.1 on 2020-01-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20191231_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('xxl', 'double extra large'), ('xxxl', 'triple extra large')], max_length=4),
        ),
        migrations.DeleteModel(
            name='ShirtSize',
        ),
    ]
