# Generated by Django 3.0.1 on 2020-01-04 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200104_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_instances',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CartProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ProductInstance')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart_product_instances',
            field=models.ManyToManyField(to='store.CartProductInstance'),
        ),
    ]
