# Generated by Django 3.0.2 on 2020-01-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200104_0259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinstance',
            unique_together={('product', 'size')},
        ),
    ]
